/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import Main.*;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author Leonardo Fronza, Heitor Ugarte Calvet da Silveira,
 */
public class App extends JFrame {

    JFileChooser jfIn;
    JFileChooser jfOut;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        JOptionPane.showMessageDialog(null, " Esta é a versão de testes permanente de 30 dias:\n "
                + "Pague 999 suaves prestações de 0,0025 centavos para remover este aviso.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buttons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbComp = new javax.swing.JRadioButton();
        rbDecomp = new javax.swing.JRadioButton();
        tfOrigem = new javax.swing.JTextField();
        tfDestino = new javax.swing.JTextField();
        btOrigem = new javax.swing.JButton();
        btDestino = new javax.swing.JButton();
        btOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho 02");
        setResizable(false);

        Buttons.add(rbComp);
        rbComp.setSelected(true);
        rbComp.setText("Compactar");

        Buttons.add(rbDecomp);
        rbDecomp.setText("Descompactar");
        rbDecomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDecompActionPerformed(evt);
            }
        });

        tfOrigem.setEnabled(false);

        tfDestino.setEnabled(false);

        btOrigem.setText("Abrir");
        btOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrigemActionPerformed(evt);
            }
        });

        btDestino.setText("Abrir");
        btDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDestinoActionPerformed(evt);
            }
        });

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Origem");

        jLabel2.setText("Destino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfOrigem)
                                .addGap(18, 18, 18)
                                .addComponent(btOrigem))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btDestino))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbComp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbDecomp)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbComp)
                .addGap(18, 18, 18)
                .addComponent(rbDecomp)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOrigem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDestino))
                .addGap(27, 27, 27)
                .addComponent(btOk)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbDecompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDecompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDecompActionPerformed

    private void btOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrigemActionPerformed
        jfIn = new JFileChooser();
        jfIn.showOpenDialog(null);
        tfOrigem.setText(jfIn.getSelectedFile().getAbsolutePath());
        if (jfOut == null) {
            if (rbComp.isSelected()) {
                tfDestino.setText(jfIn.getSelectedFile().getAbsolutePath().replaceAll(".txt", "Zip.txt"));
            } else {
                tfDestino.setText(jfIn.getSelectedFile().getAbsolutePath().replaceAll(".txt", "Unzip.txt"));
            }
        }
    }//GEN-LAST:event_btOrigemActionPerformed

    private void btDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDestinoActionPerformed
        jfOut = new JFileChooser();
        jfOut.showOpenDialog(null);
        tfDestino.setText(jfOut.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_btDestinoActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        try {
            if (rbComp.isSelected() && jfIn != null) {
                new Encriptador(jfIn.getSelectedFile(), criarArquivo());
                JOptionPane.showMessageDialog(null, "Compactação realizada com sucesso!");
            } else if (rbDecomp.isSelected() && jfIn != null) {
                new Decriptador(jfIn.getSelectedFile(), criarArquivo());
                JOptionPane.showMessageDialog(null, "Descompactação realizada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "É necessário escolher o arquivo");
            }
        } catch (IOException io) {
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado: " + io.getMessage());
        } catch (RuntimeException run) {
            JOptionPane.showMessageDialog(null, run.getLocalizedMessage());
        }

    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    private File criarArquivo() throws IOException {
        if (jfOut != null) {
            return jfOut.getSelectedFile();
        } else {
            File novoArquivo = new File(tfDestino.getText());
            novoArquivo.createNewFile(); // if file already exists will do nothing 
            new FileOutputStream(novoArquivo, false);
            return novoArquivo;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Buttons;
    private javax.swing.JButton btDestino;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btOrigem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbComp;
    private javax.swing.JRadioButton rbDecomp;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfOrigem;
    // End of variables declaration//GEN-END:variables
}
